version: '3.9'

services:
  redis:
    image: registry.gitlab.com/server1/redis/redis-master
    networks: 
      redis:
        ipv4_address: ${HOST}
    environment:
      HOST: 10.0.5.2

  redis-slave:
    image: registry.gitlab.com/server1/redis/redis-slave
    depends_on:
      - redis
    networks:
      - redis
    environment:
      MASTER_IP: 10.0.5.2
      MASTER_PORT: 6379

networks:
  redis:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/24
          gateway: 10.0.5.1