version: '3.9'

services:
  redis:
    build:
      context: ./redis-master
    networks: 
      redis:
        ipv4_address: 10.0.5.2

  redis-slave:
    build:
      context: ./redis-slave
    depends_on:
      - redis
    networks:
      - redis

networks:

  redis:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/24
          gateway: 10.0.5.1