#!/usr/bin/env python3.9

import cgi
from rediscluster import RedisCluster
from flask import Flask, render_template, request
from flask_socketio import SocketIO

app = Flask(__name__)

startup_nodes = [{"host": "redis.server.private", "port": "6379"}]
db = RedisCluster(startup_nodes=startup_nodes, decode_responses=True)
socketio = SocketIO(app)


@app.route('/')
def main():
    return render_template('main.html')


@app.route('/chatroom/<id>')
def pymeetups(id):
    print(id)
    return render_template('pymeetups.html')


@socketio.on('connect', namespace='/dd')
def ws_conn():
    c = db.incr('connected')
    socketio.emit('msg', {'count': c}, namespace='/dd')


@socketio.on('disconnect', namespace='/dd')
def ws_disconn():
    c = db.decr('connected')
    socketio.emit('msg', {'count': c}, namespace='/dd')

@socketio.on('city', namespace='/dd')
def ws_city(message):
    print(message['city'])
    socketio.emit('city', {'city': message['city']},
                  namespace="/dd")

if __name__ == '__main__':
    socketio.run(app, "0.0.0.0", port=8888)